# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

repository:
  url: https://github.com/DPotoyan/Chem167
html:
  use_repository_button: true

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url             : https://mybinder.org



latex:
  latex_documents:
    targetname: book.tex
